### ISSUE TITLE
android 15 support

### ISSUE THREAD

**Issue by david7919** [microg/android_packages_apps_GsfProxy#21]
when trying to install microg gsf on lineage os android 15 it says app not compatible

![Screenshot_20241014-164729_Package installer](https://github.com/user-attachments/assets/db8b3fff-825c-478a-8198-17d4f5718fb8)

**Comment by Lost-Entrepreneur439** [comment]
This is also present in the crDroid 11 beta (also based on Android 15).

**Comment by david79111** [comment]
Maybe it's just not relevant for the newer android versions and so they dont update the app anymore but if this is the case they should remove the checker for gsf installed for these android versions.

**Comment by david79111** [comment]
So, dev said this:
"It is used only by old apps, so it is still useful but not in all cases.
Also for GSF proxy there isn't any problem with signature checks, so you can also compile and sign yourself."

But since all my apps that depend on microg work I wont bother compiling that app but if you do feel free to share the apk and tell me if it works.

https://github.com/microg/GmsCore/issues/2623#issuecomment-2473637466

**Comment by Sapiosenses** [comment]
This is a compatibility shim for the original android push messaging service, "Cloud to Device Messaging", otherwise known as C2DM.

Given that Google says that service was deprecated in 2012 and permanently shutdown in 2015, I have no idea why anyone should care about it any more since the communications to make it work probably don't go anywhere at this point.

https://developers.google.com/android/c2dm

However: given that it's called a proxy, it may proxy attempts to use C2DM from ancient (probably pre-2012) apps and redirects them to Firebase Cloud Messaging? (FCM)

If that's the case, then it's a matter of how many people care about apps that old trying to use push notifications.

That doesn't sound like a significantly-sized ecosystem either.

**Comment by david7919** [comment]
this one works on android 15
https://github.com/micro5k/microg-unofficial-installer/raw/refs/heads/main/zip-content/origin/priv-app/GsfProxy.apk

**Comment by Sapiosenses** [comment]
> this one works on android 15 https://github.com/micro5k/microg-unofficial-installer/raw/refs/heads/main/zip-content/origin/priv-app/GsfProxy.apk

Doesn't hurt to have an A15 "compatible" one if it's just a matter of changing a couple of strings in the manifest I suppose.

But I'd be quite surprised if there were even 3 people in the entire world that would actually be impacted by that besides the error message that Google added to A13/14 and now apparently hard block on A15 for apps targeting those ancient API levels.

**Comment by hrishigodina44** [comment]
I can't access this - [https://github.com/micro5k/microg-unofficial-installer/raw/refs/heads/main/zip-content/origin/priv-app/GsfProxy.apk](url). Can anyone send me an updated apk or what needs to be changed in the [source code](https://github.com/microg/GsfProxy) so that I can generate apk myself.

**Comment by david7919** [comment]
@hrishigodina44 
Hey there, I happen to have it on my phone. But if you want instructions for building ask ale5000-git for help or take a look in his repo.
https://github.com/micro5k/microg-unofficial-installer

[GsfProxyA5K.apk.zip](https://github.com/user-attachments/files/21236006/GsfProxyA5K.apk.zip)

**Comment by hrishigodina44** [comment]
Thanks @david79111 . Let me try the apk and get back if the source code needs modifying.

**Comment by david7919** [comment]
@hrishigodina44 
You're welcome

**Comment by ale5000-git** [comment]
I have renamed it, but the file is the same.
New link: https://github.com/micro5k/microg-unofficial-installer/raw/refs/heads/main/zip-content/origin/priv-app/GsfProxyA5K.apk
